### PR TITLE
Jr/adding css modules

### PR DESCRIPTION
**Pull request by jreis13**
Why:
* Better organising of the code and easier imports.

How:
* Added and renamed files so that they use module.
* Grouped pages in folders

### CODE REVIEW

**Comment by mirhamasala** [comment]
Have you tried running this?

**Comment by jreis13** [comment]
> Have you tried running this?

Whoops, forgot about updating imports after I redid the folders etc, should be okay now

**Comment by mirhamasala** [comment]
> > Have you tried running this?
> 
> Whoops, forgot about updating imports after I redid the folders etc, should be okay now

You can change your Visual Studio Code preferences. `Code` > `Preferences` > `Settings` > 👇🏼

Screenshot 2022-07-21 at 17 46 58

**Review by mirhamasala — APPROVED** [review]

**Comment by mirhamasala** [comment]
@jreis13 Just a note: Please don't commit code with `code-review` - Give it descriptive message or squash the changes with a previous commit.

**Pull request merged**
