### PR TITLE
Add stylelint

### PR DESCRIPTION
**Pull request by mirhamasala**
Set up Stylelint

Why:

* Help avoid CSS errors and enforce conventions in our styles

This change addresses the need by:

* Installing [Stylelint](https://stylelint.io/)
* Installing `stylelint-config-standard` to extend a set of standard rules
* Adding custom rules for camelCase classes to be used with CSS modules
* Installing `stylelint-config-recess-order` to enforce declaration order
* Installing `stylelint-config-prettier` to turn off all rules that are unnecessary or might conflict with Prettier
* Specify a list of allowed property and unit pairs within declarations
* Adding scripts to run Stylelint
* Adding Stylint to GitHub Actions

### CODE REVIEW

**Comment by mirhamasala** [comment]
@joaojusto Is this something that you'd add to GitHub actions as well?

**Review by beasrodrigues24 — APPROVED** [review]

**Review by RicardoVaz1 — APPROVED** [review]

**Comment by joaojusto** [comment]
I see `px` and `rem` everywhere and my OCD is about to kill me 😂 Can we make something on stylelint about it?

**Review by joaojusto — APPROVED** [review]
This is great 🙌 Just take a look at my comment, if we can enforce unit consitency would be great!

**Comment by mirhamasala** [comment]
> This is great 🙌 Just take a look at my comment, if we can enforce unit consitency would be great!

Added these for now. We can extend as we go.

[Specify a list of allowed property and unit pairs within declarations](https://github.com/Subvisual-Academy/subvisuwheel/pull/39/commits/60602295cc258ca4c809e9829dd41040d2ebe393)

**Pull request merged**
