### PR TITLE
Wrap form elements in <form/>

### PR DESCRIPTION
**Pull request by RicardoVaz1**
Why:
* https://3.basecamp.com/4319812/buckets/26581088/todos/5256154818

How:
* Wrapping form elements in <form/>

### CODE REVIEW

**Review by mirhamasala — COMMENTED** [review]
Have you considered extracting the element into `FormLayout`?

**Comment by RicardoVaz1** [comment]
Screenshot from 2022-08-24 14-35-16

Like this?

**Comment by mirhamasala** [comment]
Better. But did you test this in your browser? 🙃 If we merge this now, this is what it looks like:

Screenshot 2022-08-25 at 07 38 32

**Comment by mirhamasala** [comment]
@RicardoVaz1 Have a look at my commits. I fixed the styles and rebased. Please make sure to check everything in the browser before opening PRs moving forward. 🙏🏼

**Review by mirhamasala — APPROVED** [review]

**Pull request merged**
