### PR TITLE
Replace linkedin url

### PR DESCRIPTION
**Pull request by jreis13**
Why:
* Linkedin URL on the seed file was not the right one.

How:
* Replaced link for the correct one.

### CODE REVIEW

**Comment by beasrodrigues24** [comment]
@jreis13 Alteraste no instagram em vez do linkedin sem querer :laughing:

**Comment by jreis13** [comment]
> @jreis13 You changed in instagram instead of linkedin accidentally 😆

bruh im old, changing it

**Review by beasrodrigues24 — APPROVED** [review]
:shipit: I waited for this moment all my life

**Comment by mirhamasala** [comment]
> > @jreis13 You changed in instagram instead of linkedin accidentally 😆
> 
> 
> 
> bruh im old, changing it

Dude. 🙈

**Pull request merged**
