### PR TITLE
Fix POST with lead information that wasn't executing

### PR DESCRIPTION
**Pull request by beasrodrigues24**
Why:
* By having href=/privacy and an onClick={handleSubmit} where the POST request with the lead information was made, it wasn't executing the POST request at all and just went to the next page

How:
* By navigating to the privacy policy using useNavigate after the post request has finished

### CODE REVIEW

**Comment by mirhamasala** [comment]
How should I arrive at this page?

If I checkout your PR, and I go straight to `/policy` I get the following error:

Screenshot 2022-08-11 at 09 28 01

**Comment by beasrodrigues24** [comment]
You should only go to policy if you fill out the sign up form. Without that it ll complain that it doesnt have the information to do the POST with the user information

**Comment by mirhamasala** [comment]
> You should only go to policy if you fill out the sign up form. Without that it ll complain that it doesnt have the information to do the POST with the user information

I did that. And I got this:

Screenshot 2022-08-11 at 10 56 36

**Comment by beasrodrigues24** [comment]
Are you testing locally or with the deploy preview? If it's with the deploy preview it shouldn't work because the branches previews can't access our heroku backend. If it's locally I might be missing a rebase. I'll check it out.

**Comment by beasrodrigues24** [comment]
It's functional on my side locally!

**Comment by mirhamasala** [comment]
> It's functional on my side locally!

Still doesn't work on my side, but go ahead. 🤷🏻‍♀️

**Review by mirhamasala — APPROVED** [review]

**Pull request merged**
