### PR TITLE
Add Sign Up page

### PR DESCRIPTION
**Pull request by beasrodrigues24**
Why:
    * Task: https://3.basecamp.com/4319812/buckets/26581088/todos/5183295453
    
How:
    * Assembling components created to be used in this page

### CODE REVIEW

**Comment by beasrodrigues24** [comment]
I think the first commit could be cherry picked to another PR. I'm gonna look on how to do that later. 
About the rest, there's some things that aren't exacly like the design that I'm gonna tweak later. Just wanted to push so it could be reviewed in the mean time!

**Comment by beasrodrigues24** [comment]
This has a lot of CSS problems that I'm gonna have to ask for help to fix :/

**Review by joaojusto — CHANGES_REQUESTED** [review]
This is almost there, I would: 
1 - Extract each "from" into a separated component"
2 - Use constants to switch between each state, ie: `const STEP_1 = "STEP_1"` or `const NAME_STEP = "NAME_STEP"`

**Comment by beasrodrigues24** [comment]
I'm confused about the constants part. Do I create them and then use them in the useState? @joaojusto

**Comment by beasrodrigues24** [comment]
The CSS is still not good at all, so if a pairing session is possible tomorrow it would be great :pray:

**Review by joaojusto — APPROVED** [review]

**Pull request merged**
