### PR TITLE
Adding redirection from route /admin to admin backoffice

### PR DESCRIPTION
**Pull request by beasrodrigues24**
Why:
* It allows us to not have to memorize another link

How:
* By creating a /admin route and an admin page that does the redirection

### CODE REVIEW

**Review by joaojusto — CHANGES_REQUESTED** [review]
I must say that I love the hack but I do think you should do the redirect using React router. I think instead of a custom `AdminPage` as a route you could use as element `<Navigate/>`. Take a look at [`Navigate`](https://reactrouter.com/docs/en/v6/components/navigate)

**Comment by beasrodrigues24** [comment]
I tried navigate but didn't find a way to make it go to an absolute path, so I went through this route. But I'll look further into it to find how it's done!

**Comment by joaojusto** [comment]
@beasrodrigues24 fair enough, maybe you're right. Did you tried with `replace`?  `<Navigate replace to="https://subvisuwheel.herokuapp.com/admin/login" />`?

**Comment by beasrodrigues24** [comment]
Sadly, same issues 
image

**Review by joaojusto — APPROVED** [review]
@beasrodrigues24 then let's merge as it is

**Pull request merged**
